export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as AppearingElement } from './AppearingElement'
export { default as Form } from './content/Form'
export { default as Nav } from './content/Nav'
export { default as Background } from './content/Background'
export { default as Gallery } from './content/Gallery'
export { default as Project } from './content/Project'